=== Josverl/micropython-stubber/data/schema/board_info-v1.json
{
    "type": "array",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Micropython board information file",
    "minItems": 1,
    "uniqueItems": true,
    "items": {
        "type": "object",
        "required": [
            "description",
            "port",
            "board",
            "board_name",
            "mcu_name",
            "path",
            "version"
        ],
        "properties": {
            "family": {
                "type": "string",
                "minLength": 1
            },
            "custom": {
                "type": "boolean"
            },
            "description": {
                "type": "string",
                "minLength": 1
            },
            "port": {
                "type": "string",
                "minLength": 1
            },
            "board": {
                "type": "string",
                "minLength": 1
            },
            "board_name": {
                "type": "string",
                "minLength": 1
            },
            "mcu_name": {
                "type": "string",
                "minLength": 1
            },
            "path": {
                "type": "string",
                "minLength": 1
            },
            "version": {
                "type": "string",
                "minLength": 1
            }
        }
    }
}

=== Josverl/micropython-stubber/src/stubber/data/board_info.json
[
    {
        "description": "4MB/OTA module with ESP32",
        "port": "esp32",
        "board": "GENERIC_OTA",
        "board_name": "4MB/OTA module",
        "mcu_name": "ESP32",
        "path": "ports/esp32/boards/GENERIC_OTA/mpconfigboard.h",
        "version": "v1.20.0"
    },
    {
        "description": "Actinius Icarus with NRF9160",
        "port": "nrf",
        "board": "ACTINIUS_ICARUS",
        "board_name": "Actinius Icarus",
        "mcu_name": "NRF9160",
        "path": "ports/nrf/boards/ACTINIUS_ICARUS/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "Adafruit Feather RP2040",
        "port": "rp2",
        "board": "ADAFRUIT_FEATHER_RP2040",
        "board_name": "Adafruit Feather RP2040",
        "mcu_name": "-",
        "path": "ports/rp2/boards/ADAFRUIT_FEATHER_RP2040/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "Adafruit Feather STM32F405 with STM32F405RG",
        "port": "stm32",
        "board": "ADAFRUIT_F405_EXPRESS",
        "board_name": "Adafruit Feather STM32F405",
        "mcu_name": "STM32F405RG",
        "path": "ports/stm32/boards/ADAFRUIT_F405_EXPRESS/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "Adafruit ItsyBitsy RP2040",
        "port": "rp2",
        "board": "ADAFRUIT_ITSYBITSY_RP2040",
        "board_name": "Adafruit ItsyBitsy RP2040",
        "mcu_name": "-",
        "path": "ports/rp2/boards/ADAFRUIT_ITSYBITSY_RP2040/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "Adafruit Metro M7 with MIMXRT1011DAE5A",
        "port": "mimxrt",
        "board": "ADAFRUIT_METRO_M7",
        "board_name": "Adafruit Metro M7",
        "mcu_name": "MIMXRT1011DAE5A",
        "path": "ports/mimxrt/boards/ADAFRUIT_METRO_M7/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "Adafruit QT Py RP2040",
        "port": "rp2",
        "board": "ADAFRUIT_QTPY_RP2040",
        "board_name": "Adafruit QT Py RP2040",
        "mcu_name": "-",
        "path": "ports/rp2/boards/ADAFRUIT_QTPY_RP2040/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "Arduino GIGA R1 WiFi with STM32H747",
        "port": "stm32",
        "board": "ARDUINO_GIGA",
        "board_name": "Arduino GIGA R1 WiFi",
        "mcu_name": "STM32H747",
        "path": "ports/stm32/boards/ARDUINO_GIGA/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "Arduino Nano 33 BLE Sense with NRF52840",
        "port": "nrf",
        "board": "ARDUINO_NANO_33_BLE_SENSE",
        "board_name": "Arduino Nano 33 BLE Sense",
        "mcu_name": "NRF52840",
        "path": "ports/nrf/boards/ARDUINO_NANO_33_BLE_SENSE/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "Arduino Nano ESP32 with ESP32S3",
        "port": "esp32",
        "board": "ARDUINO_NANO_ESP32",
        "board_name": "Arduino Nano ESP32",
        "mcu_name": "ESP32S3",
        "path": "ports/esp32/boards/ARDUINO_NANO_ESP32/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "Arduino Nano RP2040 Connect",
        "port": "rp2",
        "board": "ARDUINO_NANO_RP2040_CONNECT",
        "board_name": "Arduino Nano RP2040 Connect",
        "mcu_name": "-",
        "path": "ports/rp2/boards/ARDUINO_NANO_RP2040_CONNECT/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "Arduino Nicla Vision with STM32H747",
        "port": "stm32",
        "board": "ARDUINO_NICLA_VISION",
        "board_name": "Arduino Nicla Vision",
        "mcu_name": "STM32H747",
        "path": "ports/stm32/boards/ARDUINO_NICLA_VISION/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "Arduino Portenta C33 with RA6M5",
        "port": "renesas-ra",
        "board": "ARDUINO_PORTENTA_C33",
        "board_name": "Arduino Portenta C33",
        "mcu_name": "RA6M5",
        "path": "ports/renesas-ra/boards/ARDUINO_PORTENTA_C33/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "Arduino Portenta H7 with STM32H747",
        "port": "stm32",
        "board": "ARDUINO_PORTENTA_H7",
        "board_name": "Arduino Portenta H7",
        "mcu_name": "STM32H747",
        "path": "ports/stm32/boards/ARDUINO_PORTENTA_H7/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "Arduino Primo with NRF52832",
        "port": "nrf",
        "board": "ARDUINO_PRIMO",
        "board_name": "Arduino Primo",
        "mcu_name": "NRF52832",
        "path": "ports/nrf/boards/ARDUINO_PRIMO/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "B-L072Z-LRWAN1 with STM32L072CZ",
        "port": "stm32",
        "board": "B_L072Z_LRWAN1",
        "board_name": "B-L072Z-LRWAN1",
        "mcu_name": "STM32L072CZ",
        "path": "ports/stm32/boards/B_L072Z_LRWAN1/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "B-L475E-IOT01A with STM32L475",
        "port": "stm32",
        "board": "B_L475E_IOT01A",
        "board_name": "B-L475E-IOT01A",
        "mcu_name": "STM32L475",
        "path": "ports/stm32/boards/B_L475E_IOT01A/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "Bluefruit nRF52 Feather with NRF52832",
        "port": "nrf",
        "board": "FEATHER52",
        "board_name": "Bluefruit nRF52 Feather",
        "mcu_name": "NRF52832",
        "path": "ports/nrf/boards/FEATHER52/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "BLUEIO-TAG-EVIM with NRF52832",
        "port": "nrf",
        "board": "BLUEIO_TAG_EVIM",
        "board_name": "BLUEIO-TAG-EVIM",
        "mcu_name": "NRF52832",
        "path": "ports/nrf/boards/BLUEIO_TAG_EVIM/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "Cerb40 with STM32F405RG",
        "port": "stm32",
        "board": "CERB40",
        "board_name": "Cerb40",
        "mcu_name": "STM32F405RG",
        "path": "ports/stm32/boards/CERB40/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "CustomPCB with STM32F439",
        "port": "stm32",
        "board": "STM32F439",
        "board_name": "CustomPCB",
        "mcu_name": "STM32F439",
        "path": "ports/stm32/boards/STM32F439/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "DVK-BL652 with NRF52832",
        "port": "nrf",
        "board": "DVK_BL652",
        "board_name": "DVK-BL652",
        "mcu_name": "NRF52832",
        "path": "ports/nrf/boards/DVK_BL652/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "EK-RA4M1 with RA4M1",
        "port": "renesas-ra",
        "board": "EK_RA4M1",
        "board_name": "EK-RA4M1",
        "mcu_name": "RA4M1",
        "path": "ports/renesas-ra/boards/EK_RA4M1/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "EK-RA4W1 with RA4W1",
        "port": "renesas-ra",
        "board": "EK_RA4W1",
        "board_name": "EK-RA4W1",
        "mcu_name": "RA4W1",
        "path": "ports/renesas-ra/boards/EK_RA4W1/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "EK-RA6M1 with RA6M1",
        "port": "renesas-ra",
        "board": "EK_RA6M1",
        "board_name": "EK-RA6M1",
        "mcu_name": "RA6M1",
        "path": "ports/renesas-ra/boards/EK_RA6M1/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "EK-RA6M2 with RA6M2",
        "port": "renesas-ra",
        "board": "EK_RA6M2",
        "board_name": "EK-RA6M2",
        "mcu_name": "RA6M2",
        "path": "ports/renesas-ra/boards/EK_RA6M2/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "ESP module (1M) with ESP8266",
        "port": "esp8266",
        "board": "ESP8266_GENERIC",
        "board_name": "ESP module (1M)",
        "mcu_name": "ESP8266",
        "path": "ports/esp8266/boards/ESP8266_GENERIC/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "ESP module (512K) with ESP8266",
        "port": "esp8266",
        "board": "ESP8266_GENERIC",
        "board_name": "ESP module (512K)",
        "mcu_name": "ESP8266",
        "path": "ports/esp8266/boards/ESP8266_GENERIC/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "ESP module with ESP8266",
        "port": "esp8266",
        "board": "ESP8266_GENERIC",
        "board_name": "ESP module",
        "mcu_name": "ESP8266",
        "path": "ports/esp8266/boards/ESP8266_GENERIC/mpconfigboard.h",
        "version": "v1.22.0"
    },
    {
        "description": "ESP32 module (spiram) with ESP32",
        "port": "esp32",
        "board": "GENERIC_SPIRAM",
        "board_name": "ESP32 module (spiram)",
        "mcu_name": "ESP32",
        "path": "ports/esp32/boards/GENERIC_SPIRAM/mpconfigboard.h",
        "version": "v1.20.0"
    },
    {
        "description": "ESP32 module with ESP32",
        "port": "esp32",
        "board": "GENERIC",
        "board_name": "ESP32 module",
        "mcu_name": "ESP32",
        "path": "ports/esp32/boards/GENERIC/mpconfigboard.h",
        "version": "v1.20.0"
    },
    {
        "description": "ESP32 Unicore module with ESP32-UNICORE",
        "port": "esp32",
        "board": "GENERIC_UNICORE",
        "board_name": "ESP32 Unicore module",
        "mcu_name": "ESP32-UNICORE",
        "path": "ports/esp32/boards/GENERIC_UNICORE/mpconfigboard.h",
        "version": "v1.20.0"
    },
    {
        "description": "ESP32-D2WD",
        "port": "esp32",
        "board": "ESP32_GENERIC",
        "board_name": "-",
        "mcu_name": "-",
        "path": "ports/esp32/boards/ESP32_GENERIC/mpconfigboard.cmake",
        "version": "v1.22.0"
    },
    {
        "description": "ESP32-S2-WROVER with ESP32-S2",
